---
- name: Back up EOS configuration
  hosts: eos
  gather_facts: false
  become: true
  tasks:
    - name: Create backup
      arista.eos.eos_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}.backup.cfg"
          dir_path: /tmp

- name: Copy backup file to exercise directory
  hosts: workstation.lab.example.com
  gather_facts: false
  become: true
  become_user: student
  tasks:
    - name: Copy backup file
      ansible.builtin.copy:
        src: /tmp/{{ item }}.backup.cfg
        dest: /home/student/example-chat/
      loop: "{{ groups['eos'] }}"
