---
- name: Arista events
  hosts: all
  sources:
    - name: Collect events from Apache Kafka
      ansible.eda.kafka:
        host: utility.lab.example.com
        port: 9092
        topic: network

  rules:
    - name: Port is down
      condition: event.body.fields.admin_status == "DOWN"
      action:
        run_job_template:
          name: Manage Arista network interfaces
          organization: Default
          post_events: true
